import React, { useState } from 'react';
import { useTopics } from '../../hooks/useTopics';
import { useCreators } from '../../hooks/useCreators';
import { authService } from '../../config/auth';
import TopicForm from './TopicForm';
import VideoForm from './VideoForm';
import AdminList from './AdminList';

const AdminPage = () => {
  const { topics, addTopic, updateTopic, deleteTopic, addVideo, deleteVideo, deleteTopicsWithPriorityOver30 } = useTopics();
  const { creators, addCreator, deleteCreator } = useCreators();
  const [view, setView] = useState('list'); // 'list', 'addTopic', 'editTopic', 'addVideo', 'creators'
  const [selectedTopic, setSelectedTopic] = useState(null);
  const [newCreatorName, setNewCreatorName] = useState('');

  console.log('AdminPage topics:', topics);

  const handleLogout = async () => {
    await authService.signOut();
    window.location.href = '/admin/login';
  };

  const handleAddTopic = (topicData) => {
    console.log('Adding topic data:', topicData);
    addTopic({
      ...topicData
      // ID will be auto-generated by database
    });
    setView('list');
  };

  const handleUpdateTopic = (topicData) => {
    updateTopic(selectedTopic.id, topicData);
    setSelectedTopic(null);
    setView('list');
  };

  const handleAddVideo = (videoData) => {
    console.log('Adding video data:', videoData);
    console.log('To topic ID:', selectedTopic.id);
    addVideo(selectedTopic.id, {
      ...videoData,
      id: Date.now().toString()
    });
    setSelectedTopic(null);
    setView('list');
  };

  const handleEditTopic = (topic) => {
    setSelectedTopic(topic);
    setView('editTopic');
  };

  const handleAddVideoToTopic = (topic) => {
    setSelectedTopic(topic);
    setView('addVideo');
  };

  const handleAddCreator = (e) => {
    e.preventDefault();
    if (newCreatorName.trim()) {
      addCreator(newCreatorName.trim());
      setNewCreatorName('');
    }
  };

  const handleDeleteCreator = (creatorName) => {
    if (confirm(`Delete creator "${creatorName}"? This won't delete videos, but you won't be able to select this creator for new videos.`)) {
      deleteCreator(creatorName);
    }
  };

  const handleDeleteLowPriorityTopics = async () => {
    const topicsOver30 = topics.filter(t => t.priority > 30).length;
    if (topicsOver30 === 0) {
      alert('No topics with priority greater than 30 to delete.');
      return;
    }
    
    if (confirm(`Delete ${topicsOver30} topic(s) with priority greater than 30?`)) {
      await deleteTopicsWithPriorityOver30();
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-gray-900 text-white shadow-lg">
        <div className="max-w-6xl mx-auto px-4 py-4">
          <div className="flex justify-between items-center">
            <h1 className="text-2xl font-bold">Admin Panel</h1>
            <div className="flex gap-2">
              <a
                href="/"
                className="px-4 py-2 bg-gray-700 text-white rounded hover:bg-gray-600 transition-colors text-sm font-medium"
              >
                Back to Home
              </a>
              <button
                onClick={handleLogout}
                className="px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700 transition-colors text-sm font-medium"
              >
                Logout
              </button>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 py-8">
        {/* Tab Navigation */}
        <div className="flex gap-4 mb-6 border-b">
          <button
            onClick={() => setView('list')}
            className={`px-4 py-2 font-medium transition-colors ${
              view === 'list' || view === 'addTopic' || view === 'editTopic' || view === 'addVideo'
                ? 'border-b-2 border-blue-600 text-blue-600'
                : 'text-gray-600 hover:text-gray-900'
            }`}
          >
            Topics & Videos
          </button>
          <button
            onClick={() => setView('creators')}
            className={`px-4 py-2 font-medium transition-colors ${
              view === 'creators'
                ? 'border-b-2 border-blue-600 text-blue-600'
                : 'text-gray-600 hover:text-gray-900'
            }`}
          >
            Manage Creators
          </button>
        </div>

        {view === 'list' && (
          <div>
            <div className="mb-6 flex gap-4">
              <button
                onClick={() => setView('addTopic')}
                className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium"
              >
                + Add New Topic
              </button>
              <button
                onClick={handleDeleteLowPriorityTopics}
                className="px-6 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors font-medium"
              >
                Delete Topics Priority &gt; 30
              </button>
            </div>
            <AdminList
              topics={topics}
              onEdit={handleEditTopic}
              onDelete={deleteTopic}
              onAddVideo={handleAddVideoToTopic}
              onDeleteVideo={deleteVideo}
            />
          </div>
        )}

        {view === 'addTopic' && (
          <div>
            <div className="mb-4">
              <button
                onClick={() => setView('list')}
                className="text-blue-600 hover:text-blue-700 font-medium"
              >
                ← Back to list
              </button>
            </div>
            <h2 className="text-2xl font-bold mb-6">Add New Topic</h2>
            <TopicForm onSubmit={handleAddTopic} existingTopics={topics} />
          </div>
        )}

        {view === 'editTopic' && selectedTopic && (
          <div>
            <div className="mb-4">
              <button
                onClick={() => { setView('list'); setSelectedTopic(null); }}
                className="text-blue-600 hover:text-blue-700 font-medium"
              >
                ← Back to list
              </button>
            </div>
            <h2 className="text-2xl font-bold mb-6">Edit Topic</h2>
            <TopicForm
              initialTopic={selectedTopic}
              onSubmit={handleUpdateTopic}
            />
          </div>
        )}

        {view === 'addVideo' && selectedTopic && (
          <div>
            <div className="mb-4">
              <button
                onClick={() => { setView('list'); setSelectedTopic(null); }}
                className="text-blue-600 hover:text-blue-700 font-medium"
              >
                ← Back to list
              </button>
            </div>
            <h2 className="text-2xl font-bold mb-6">
              Add Video to "{selectedTopic.title}"
            </h2>
            <VideoForm onSubmit={handleAddVideo} creators={creators} />
          </div>
        )}

        {view === 'creators' && (
          <div>
            <h2 className="text-2xl font-bold mb-6">Manage Creators</h2>
            
            {/* Add Creator Form */}
            <div className="bg-white rounded-lg shadow p-6 mb-6">
              <h3 className="text-lg font-semibold mb-4">Add New Creator</h3>
              <form onSubmit={handleAddCreator} className="flex gap-3">
                <input
                  type="text"
                  value={newCreatorName}
                  onChange={(e) => setNewCreatorName(e.target.value)}
                  placeholder="Creator/Channel name (e.g., Palki Sharma)"
                  className="flex-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  required
                />
                <button
                  type="submit"
                  className="px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors font-medium"
                >
                  Add Creator
                </button>
              </form>
            </div>

            {/* Creators List */}
            <div className="bg-white rounded-lg shadow p-6">
              <h3 className="text-lg font-semibold mb-4">All Creators ({creators.length})</h3>
              {creators.length === 0 ? (
                <p className="text-gray-500 italic">No creators yet. Add your first creator above.</p>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                  {creators.map((creator) => (
                    <div
                      key={creator}
                      className="flex justify-between items-center p-3 bg-gray-50 rounded border hover:bg-gray-100 transition-colors"
                    >
                      <span className="font-medium text-gray-900">{creator}</span>
                      <button
                        onClick={() => handleDeleteCreator(creator)}
                        className="px-3 py-1 bg-red-500 text-white text-xs rounded hover:bg-red-600 transition-colors"
                      >
                        Delete
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default AdminPage;
